//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerTreeView.Settings.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServerTreeView.Settings.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad format assembly..
        /// </summary>
        internal static string AssemblyBadFormatException {
            get {
                return ResourceManager.GetString("AssemblyBadFormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServerTreeView.
        /// </summary>
        internal static string AssemblyFileName {
            get {
                return ResourceManager.GetString("AssemblyFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServerTreeView assembly is not registered in global assembly cache.: {0}.
        /// </summary>
        internal static string AssemblyIsNotRegistered {
            get {
                return ResourceManager.GetString("AssemblyIsNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string AssemblyLabel {
            get {
                return ResourceManager.GetString("AssemblyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading the assembly from GAC..
        /// </summary>
        internal static string AssemblyLoadException {
            get {
                return ResourceManager.GetString("AssemblyLoadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly not found in GAC..
        /// </summary>
        internal static string AssemblyNotFoundException {
            get {
                return ResourceManager.GetString("AssemblyNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient permission to load the assembly from GAC..
        /// </summary>
        internal static string AssemblyPermissionException {
            get {
                return ResourceManager.GetString("AssemblyPermissionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Settings.
        /// </summary>
        internal static string CaptionAdvancedSettings {
            get {
                return ResourceManager.GetString("CaptionAdvancedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string CaptionError {
            get {
                return ResourceManager.GetString("CaptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to csv files (*.csv)|*.csv.
        /// </summary>
        internal static string CsvFileFilter {
            get {
                return ResourceManager.GetString("CsvFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A login request is initiated..
        /// </summary>
        internal static string DefaultNotificationMessage {
            get {
                return ResourceManager.GetString("DefaultNotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while reading file from disk..
        /// </summary>
        internal static string DiskReadError {
            get {
                return ResourceManager.GetString("DiskReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Failed to add an application to iis server: {0}.
        /// </summary>
        internal static string ErrorAddingAppDirectorytoServer {
            get {
                return ResourceManager.GetString("ErrorAddingAppDirectorytoServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while adding module in web config for selected site : {0}.
        /// </summary>
        internal static string ErroraddingModuleInWebConfig {
            get {
                return ResourceManager.GetString("ErroraddingModuleInWebConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Failed to commit changes to IIS server: {0}.
        /// </summary>
        internal static string ErrorCommittingChangestoServer {
            get {
                return ResourceManager.GetString("ErrorCommittingChangestoServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while deleting module web application from IIS site : {0}.
        /// </summary>
        internal static string ErrorDeletingAppDirectoryFromServer {
            get {
                return ResourceManager.GetString("ErrorDeletingAppDirectoryFromServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while deleting module element from IIS web application : {0}.
        /// </summary>
        internal static string ErrorDeletingModuleElementFromServer {
            get {
                return ResourceManager.GetString("ErrorDeletingModuleElementFromServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to initialize the list of available websites in IIS server : {0}.
        /// </summary>
        internal static string ErrorInitializeWebSites {
            get {
                return ResourceManager.GetString("ErrorInitializeWebSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while refreshing the server site..
        /// </summary>
        internal static string ErrorInServerEvents {
            get {
                return ResourceManager.GetString("ErrorInServerEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid subscription key.
        /// </summary>
        internal static string ErrorMessageSubscriptionKey {
            get {
                return ResourceManager.GetString("ErrorMessageSubscriptionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read the settings from config file : {0}.
        /// </summary>
        internal static string ErrorReadingConfigFile {
            get {
                return ResourceManager.GetString("ErrorReadingConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read the protected site settings values from config file : {0}.
        /// </summary>
        internal static string ErrorReadingProtectedSiteSettings {
            get {
                return ResourceManager.GetString("ErrorReadingProtectedSiteSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read registry key : {0}.
        /// </summary>
        internal static string ErrorReadingRegistry {
            get {
                return ResourceManager.GetString("ErrorReadingRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry key cannot be null or empty..
        /// </summary>
        internal static string ErrorReadingRegistryKey {
            get {
                return ResourceManager.GetString("ErrorReadingRegistryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read or view registry key : {0}.
        /// </summary>
        internal static string ErrorReadingRegistryKeyandView {
            get {
                return ResourceManager.GetString("ErrorReadingRegistryKeyandView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user doesn&apos;t have the necessary registry rights : {0}.
        /// </summary>
        internal static string ErrorReadingRegistryKeyPermission {
            get {
                return ResourceManager.GetString("ErrorReadingRegistryKeyPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user doesn&apos;t have permissions required to read this registry : {0}.
        /// </summary>
        internal static string ErrorReadingRegistryKeySecurity {
            get {
                return ResourceManager.GetString("ErrorReadingRegistryKeySecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read IIS server configuration..
        /// </summary>
        internal static string ErrorReadingServer {
            get {
                return ResourceManager.GetString("ErrorReadingServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read site details on {0} IIS server.
        /// </summary>
        internal static string ErrorReadingServerSite {
            get {
                return ResourceManager.GetString("ErrorReadingServerSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read {0} application from IIS server..
        /// </summary>
        internal static string ErrorReadingServerSiteApplication {
            get {
                return ResourceManager.GetString("ErrorReadingServerSiteApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read IIS server sites..
        /// </summary>
        internal static string ErrorReadingServerSites {
            get {
                return ResourceManager.GetString("ErrorReadingServerSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read {0} application from IIS server..
        /// </summary>
        internal static string ErrorReadingServerSiteVirtualDirectory {
            get {
                return ResourceManager.GetString("ErrorReadingServerSiteVirtualDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while removing web module from IIS site : {0}.
        /// </summary>
        internal static string ErrorRemovingAppDirectoryFromServer {
            get {
                return ResourceManager.GetString("ErrorRemovingAppDirectoryFromServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while adding Remove Element in web config for selected site : {0}.
        /// </summary>
        internal static string ErrorRemovingModuleInWebConfig {
            get {
                return ResourceManager.GetString("ErrorRemovingModuleInWebConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while refreshing the server site : {0}.
        /// </summary>
        internal static string ErrorRestartWebSite {
            get {
                return ResourceManager.GetString("ErrorRestartWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save user repository settings : {0}.
        /// </summary>
        internal static string ErrorSavingActiveDirectorySettings {
            get {
                return ResourceManager.GetString("ErrorSavingActiveDirectorySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save configuration settings : {0}.
        /// </summary>
        internal static string ErrorSavingConfigFile {
            get {
                return ResourceManager.GetString("ErrorSavingConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save the protected site settings value in config file : {0}.
        /// </summary>
        internal static string ErrorSavingProtectedSiteSettings {
            get {
                return ResourceManager.GetString("ErrorSavingProtectedSiteSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter shared secret..
        /// </summary>
        internal static string ErrorSharedSecret {
            get {
                return ResourceManager.GetString("ErrorSharedSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update web config. : {0}.
        /// </summary>
        internal static string ErrorUpdatingModuleInWebConfig {
            get {
                return ResourceManager.GetString("ErrorUpdatingModuleInWebConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to Active Directory domain services..
        /// </summary>
        internal static string ErrorValidateCredentials {
            get {
                return ResourceManager.GetString("ErrorValidateCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while applying the settings for selected server sites..
        /// </summary>
        internal static string ErrorValidateProtectedSiteSettings {
            get {
                return ResourceManager.GetString("ErrorValidateProtectedSiteSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Windows\Microsoft.NET\assembly\GAC_MSIL.
        /// </summary>
        internal static string GlobalAssemblyPath {
            get {
                return ResourceManager.GetString("GlobalAssemblyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W3SVC.
        /// </summary>
        internal static string IISServiceName {
            get {
                return ResourceManager.GetString("IISServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to launch the configuration tool. Unable to connect to IIS server. .
        /// </summary>
        internal static string IsServerRunning {
            get {
                return ResourceManager.GetString("IsServerRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string LabelApply {
            get {
                return ResourceManager.GetString("LabelApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string LabelCancel {
            get {
                return ResourceManager.GetString("LabelCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string LabelOk {
            get {
                return ResourceManager.GetString("LabelOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protected server sites.
        /// </summary>
        internal static string LabelProtectedSites {
            get {
                return ResourceManager.GetString("LabelProtectedSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the repository where list of users are stored..
        /// </summary>
        internal static string LabelSelectRepository {
            get {
                return ResourceManager.GetString("LabelSelectRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started website : {0}.
        /// </summary>
        internal static string MessageServerStart {
            get {
                return ResourceManager.GetString("MessageServerStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped website : {0}.
        /// </summary>
        internal static string MessageServerStop {
            get {
                return ResourceManager.GetString("MessageServerStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string Module {
            get {
                return ResourceManager.GetString("Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Module.
        /// </summary>
        internal static string ModuleAppDirectoryName {
            get {
                return ResourceManager.GetString("ModuleAppDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Module.dll&quot;.
        /// </summary>
        internal static string ModuleAssemblyName {
            get {
                return ResourceManager.GetString("ModuleAssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        internal static string ModuleName {
            get {
                return ResourceManager.GetString("ModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthenticationModule.
        /// </summary>
        internal static string ModuleNameSpace {
            get {
                return ResourceManager.GetString("ModuleNameSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to managedHandler.
        /// </summary>
        internal static string ModuleType {
            get {
                return ResourceManager.GetString("ModuleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to launch the configuration tool. No website(s) available in IIS server..
        /// </summary>
        internal static string NoRegisteredServerSite {
            get {
                return ResourceManager.GetString("NoRegisteredServerSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a site or web application to apply settings..
        /// </summary>
        internal static string NoSiteSelectedForAuthentication {
            get {
                return ResourceManager.GetString("NoSiteSelectedForAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software\\Module.
        /// </summary>
        internal static string RegistryKeyPath {
            get {
                return ResourceManager.GetString("RegistryKeyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove.
        /// </summary>
        internal static string remove {
            get {
                return ResourceManager.GetString("remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A restart of modified site(s) is required for changes to take effect. Do you want to restart now?.
        /// </summary>
        internal static string RestartConfirmBoxMessage {
            get {
                return ResourceManager.GetString("RestartConfirmBoxMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A restart of IIS server is required for changes to take effect. Do you want to restart now?.
        /// </summary>
        internal static string RestartServerConfirmBoxMessage {
            get {
                return ResourceManager.GetString("RestartServerConfirmBoxMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while restarting IIS server..
        /// </summary>
        internal static string RestartServerError {
            get {
                return ResourceManager.GetString("RestartServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarting selected site(s)..
        /// </summary>
        internal static string RestartServerSiteMessage {
            get {
                return ResourceManager.GetString("RestartServerSiteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to launch the configuration tool. The requested operation requires elevated permissions..
        /// </summary>
        internal static string RunAsAdministrator {
            get {
                return ResourceManager.GetString("RunAsAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to system.webServer/modules.
        /// </summary>
        internal static string ServerConfigModuleAttribute {
            get {
                return ResourceManager.GetString("ServerConfigModuleAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iisreset.exe.
        /// </summary>
        internal static string serverexecutable {
            get {
                return ResourceManager.GetString("serverexecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to localhost.
        /// </summary>
        internal static string ServerIpAddress {
            get {
                return ResourceManager.GetString("ServerIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server name.
        /// </summary>
        internal static string ServerName {
            get {
                return ResourceManager.GetString("ServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server settings.
        /// </summary>
        internal static string ServerSettings {
            get {
                return ResourceManager.GetString("ServerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To protect the server sites (root node) with Two-Factor authentication, select its check box.To 
        ///unprotect, clear its checkbox. Only selected web application(s) under the server site will be 
        ///protected..
        /// </summary>
        internal static string ServerSiteMessage {
            get {
                return ResourceManager.GetString("ServerSiteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while starting the application.If the error occurs again, contact your administrator..
        /// </summary>
        internal static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
    }
}
